package cn.edu.xmu.oomall.transaction.mapper;

import cn.edu.xmu.oomall.transaction.model.po.PaymentPatternPo;
import cn.edu.xmu.oomall.transaction.model.po.PaymentPatternPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentPatternPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentPatternPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int insert(PaymentPatternPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int insertSelective(PaymentPatternPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    List<PaymentPatternPo> selectByExample(PaymentPatternPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    PaymentPatternPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaymentPatternPo record, @Param("example") PaymentPatternPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaymentPatternPo record, @Param("example") PaymentPatternPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentPatternPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentPatternPo record);
}