package cn.edu.xmu.oomall.transaction.mapper;

import cn.edu.xmu.oomall.transaction.model.po.RefundPo;
import cn.edu.xmu.oomall.transaction.model.po.RefundPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int deleteByExample(RefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int insert(RefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int insertSelective(RefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    List<RefundPo> selectByExample(RefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    RefundPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RefundPo record, @Param("example") RefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RefundPo record, @Param("example") RefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RefundPo record);
}