package cn.edu.xmu.oomall.order.mapper;

import cn.edu.xmu.oomall.order.model.po.OrderPo;
import cn.edu.xmu.oomall.order.model.po.OrderPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int deleteByExample(OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int insert(OrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int insertSelective(OrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    List<OrderPo> selectByExample(OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    OrderPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderPo record, @Param("example") OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderPo record, @Param("example") OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderPo record);
}