package cn.edu.xmu.oomall.transaction.model.po;

import java.time.LocalDateTime;

public class ErrorAccountPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.trade_sn
     *
     * @mbg.generated
     */
    private String tradeSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.pattern_id
     *
     * @mbg.generated
     */
    private Long patternId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.income
     *
     * @mbg.generated
     */
    private Long income;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.expenditure
     *
     * @mbg.generated
     */
    private Long expenditure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.document_id
     *
     * @mbg.generated
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.time
     *
     * @mbg.generated
     */
    private LocalDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.descr
     *
     * @mbg.generated
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.adjust_id
     *
     * @mbg.generated
     */
    private Long adjustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.adjust_name
     *
     * @mbg.generated
     */
    private String adjustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.adjust_time
     *
     * @mbg.generated
     */
    private LocalDateTime adjustTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_error_account.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.id
     *
     * @return the value of oomall_error_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.id
     *
     * @param id the value for oomall_error_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.trade_sn
     *
     * @return the value of oomall_error_account.trade_sn
     *
     * @mbg.generated
     */
    public String getTradeSn() {
        return tradeSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.trade_sn
     *
     * @param tradeSn the value for oomall_error_account.trade_sn
     *
     * @mbg.generated
     */
    public void setTradeSn(String tradeSn) {
        this.tradeSn = tradeSn == null ? null : tradeSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.pattern_id
     *
     * @return the value of oomall_error_account.pattern_id
     *
     * @mbg.generated
     */
    public Long getPatternId() {
        return patternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.pattern_id
     *
     * @param patternId the value for oomall_error_account.pattern_id
     *
     * @mbg.generated
     */
    public void setPatternId(Long patternId) {
        this.patternId = patternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.income
     *
     * @return the value of oomall_error_account.income
     *
     * @mbg.generated
     */
    public Long getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.income
     *
     * @param income the value for oomall_error_account.income
     *
     * @mbg.generated
     */
    public void setIncome(Long income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.expenditure
     *
     * @return the value of oomall_error_account.expenditure
     *
     * @mbg.generated
     */
    public Long getExpenditure() {
        return expenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.expenditure
     *
     * @param expenditure the value for oomall_error_account.expenditure
     *
     * @mbg.generated
     */
    public void setExpenditure(Long expenditure) {
        this.expenditure = expenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.document_id
     *
     * @return the value of oomall_error_account.document_id
     *
     * @mbg.generated
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.document_id
     *
     * @param documentId the value for oomall_error_account.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.state
     *
     * @return the value of oomall_error_account.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.state
     *
     * @param state the value for oomall_error_account.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.time
     *
     * @return the value of oomall_error_account.time
     *
     * @mbg.generated
     */
    public LocalDateTime getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.time
     *
     * @param time the value for oomall_error_account.time
     *
     * @mbg.generated
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.descr
     *
     * @return the value of oomall_error_account.descr
     *
     * @mbg.generated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.descr
     *
     * @param descr the value for oomall_error_account.descr
     *
     * @mbg.generated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.adjust_id
     *
     * @return the value of oomall_error_account.adjust_id
     *
     * @mbg.generated
     */
    public Long getAdjustId() {
        return adjustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.adjust_id
     *
     * @param adjustId the value for oomall_error_account.adjust_id
     *
     * @mbg.generated
     */
    public void setAdjustId(Long adjustId) {
        this.adjustId = adjustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.adjust_name
     *
     * @return the value of oomall_error_account.adjust_name
     *
     * @mbg.generated
     */
    public String getAdjustName() {
        return adjustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.adjust_name
     *
     * @param adjustName the value for oomall_error_account.adjust_name
     *
     * @mbg.generated
     */
    public void setAdjustName(String adjustName) {
        this.adjustName = adjustName == null ? null : adjustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.adjust_time
     *
     * @return the value of oomall_error_account.adjust_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAdjustTime() {
        return adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.adjust_time
     *
     * @param adjustTime the value for oomall_error_account.adjust_time
     *
     * @mbg.generated
     */
    public void setAdjustTime(LocalDateTime adjustTime) {
        this.adjustTime = adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.creator_id
     *
     * @return the value of oomall_error_account.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.creator_id
     *
     * @param creatorId the value for oomall_error_account.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.creator_name
     *
     * @return the value of oomall_error_account.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.creator_name
     *
     * @param creatorName the value for oomall_error_account.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.modifier_id
     *
     * @return the value of oomall_error_account.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.modifier_id
     *
     * @param modifierId the value for oomall_error_account.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.modifier_name
     *
     * @return the value of oomall_error_account.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.modifier_name
     *
     * @param modifierName the value for oomall_error_account.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.gmt_create
     *
     * @return the value of oomall_error_account.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.gmt_create
     *
     * @param gmtCreate the value for oomall_error_account.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_error_account.gmt_modified
     *
     * @return the value of oomall_error_account.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_error_account.gmt_modified
     *
     * @param gmtModified the value for oomall_error_account.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}