package cn.edu.xmu.oomall.transaction.model.po;

import java.time.LocalDateTime;

public class PaymentPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.trade_sn
     *
     * @mbg.generated
     */
    private String tradeSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.pattern_id
     *
     * @mbg.generated
     */
    private Long patternId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.actual_amount
     *
     * @mbg.generated
     */
    private Long actualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.document_id
     *
     * @mbg.generated
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.document_type
     *
     * @mbg.generated
     */
    private Byte documentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.pay_time
     *
     * @mbg.generated
     */
    private LocalDateTime payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.begin_time
     *
     * @mbg.generated
     */
    private LocalDateTime beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.descr
     *
     * @mbg.generated
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.adjust_id
     *
     * @mbg.generated
     */
    private Long adjustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.adjust_name
     *
     * @mbg.generated
     */
    private String adjustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.adjust_time
     *
     * @mbg.generated
     */
    private LocalDateTime adjustTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_payment.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.id
     *
     * @return the value of oomall_payment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.id
     *
     * @param id the value for oomall_payment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.trade_sn
     *
     * @return the value of oomall_payment.trade_sn
     *
     * @mbg.generated
     */
    public String getTradeSn() {
        return tradeSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.trade_sn
     *
     * @param tradeSn the value for oomall_payment.trade_sn
     *
     * @mbg.generated
     */
    public void setTradeSn(String tradeSn) {
        this.tradeSn = tradeSn == null ? null : tradeSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.pattern_id
     *
     * @return the value of oomall_payment.pattern_id
     *
     * @mbg.generated
     */
    public Long getPatternId() {
        return patternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.pattern_id
     *
     * @param patternId the value for oomall_payment.pattern_id
     *
     * @mbg.generated
     */
    public void setPatternId(Long patternId) {
        this.patternId = patternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.amount
     *
     * @return the value of oomall_payment.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.amount
     *
     * @param amount the value for oomall_payment.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.actual_amount
     *
     * @return the value of oomall_payment.actual_amount
     *
     * @mbg.generated
     */
    public Long getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.actual_amount
     *
     * @param actualAmount the value for oomall_payment.actual_amount
     *
     * @mbg.generated
     */
    public void setActualAmount(Long actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.document_id
     *
     * @return the value of oomall_payment.document_id
     *
     * @mbg.generated
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.document_id
     *
     * @param documentId the value for oomall_payment.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.document_type
     *
     * @return the value of oomall_payment.document_type
     *
     * @mbg.generated
     */
    public Byte getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.document_type
     *
     * @param documentType the value for oomall_payment.document_type
     *
     * @mbg.generated
     */
    public void setDocumentType(Byte documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.pay_time
     *
     * @return the value of oomall_payment.pay_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.pay_time
     *
     * @param payTime the value for oomall_payment.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(LocalDateTime payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.begin_time
     *
     * @return the value of oomall_payment.begin_time
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.begin_time
     *
     * @param beginTime the value for oomall_payment.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.end_time
     *
     * @return the value of oomall_payment.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.end_time
     *
     * @param endTime the value for oomall_payment.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.state
     *
     * @return the value of oomall_payment.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.state
     *
     * @param state the value for oomall_payment.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.descr
     *
     * @return the value of oomall_payment.descr
     *
     * @mbg.generated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.descr
     *
     * @param descr the value for oomall_payment.descr
     *
     * @mbg.generated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.adjust_id
     *
     * @return the value of oomall_payment.adjust_id
     *
     * @mbg.generated
     */
    public Long getAdjustId() {
        return adjustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.adjust_id
     *
     * @param adjustId the value for oomall_payment.adjust_id
     *
     * @mbg.generated
     */
    public void setAdjustId(Long adjustId) {
        this.adjustId = adjustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.adjust_name
     *
     * @return the value of oomall_payment.adjust_name
     *
     * @mbg.generated
     */
    public String getAdjustName() {
        return adjustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.adjust_name
     *
     * @param adjustName the value for oomall_payment.adjust_name
     *
     * @mbg.generated
     */
    public void setAdjustName(String adjustName) {
        this.adjustName = adjustName == null ? null : adjustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.adjust_time
     *
     * @return the value of oomall_payment.adjust_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAdjustTime() {
        return adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.adjust_time
     *
     * @param adjustTime the value for oomall_payment.adjust_time
     *
     * @mbg.generated
     */
    public void setAdjustTime(LocalDateTime adjustTime) {
        this.adjustTime = adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.creator_id
     *
     * @return the value of oomall_payment.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.creator_id
     *
     * @param creatorId the value for oomall_payment.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.creator_name
     *
     * @return the value of oomall_payment.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.creator_name
     *
     * @param creatorName the value for oomall_payment.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.modifier_id
     *
     * @return the value of oomall_payment.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.modifier_id
     *
     * @param modifierId the value for oomall_payment.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.modifier_name
     *
     * @return the value of oomall_payment.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.modifier_name
     *
     * @param modifierName the value for oomall_payment.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.gmt_create
     *
     * @return the value of oomall_payment.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.gmt_create
     *
     * @param gmtCreate the value for oomall_payment.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_payment.gmt_modified
     *
     * @return the value of oomall_payment.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_payment.gmt_modified
     *
     * @param gmtModified the value for oomall_payment.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}