package cn.edu.xmu.oomall.ooad201.payment.mapper;

import cn.edu.xmu.oomall.ooad201.payment.model.po.ErrorAccountPo;
import cn.edu.xmu.oomall.ooad201.payment.model.po.ErrorAccountPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorAccountPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int deleteByExample(ErrorAccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int insert(ErrorAccountPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int insertSelective(ErrorAccountPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    List<ErrorAccountPo> selectByExample(ErrorAccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    ErrorAccountPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ErrorAccountPo record, @Param("example") ErrorAccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ErrorAccountPo record, @Param("example") ErrorAccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ErrorAccountPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ErrorAccountPo record);
}