package cn.edu.xmu.oomall.ooad201.payment.mapper;

import cn.edu.xmu.oomall.ooad201.payment.model.po.ErrorPaymentPo;
import cn.edu.xmu.oomall.ooad201.payment.model.po.ErrorPaymentPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorPaymentPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int deleteByExample(ErrorPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int insert(ErrorPaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int insertSelective(ErrorPaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    List<ErrorPaymentPo> selectByExample(ErrorPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    ErrorPaymentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ErrorPaymentPo record, @Param("example") ErrorPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ErrorPaymentPo record, @Param("example") ErrorPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ErrorPaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_error_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ErrorPaymentPo record);
}