package cn.edu.xmu.oomall.ooad201.payment.mapper;

import cn.edu.xmu.oomall.ooad201.payment.model.po.PaymentPatternPo;
import cn.edu.xmu.oomall.ooad201.payment.model.po.PaymentPatternPoExample;
import java.util.List;

public interface PaymentPatternPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int insert(PaymentPatternPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int insertSelective(PaymentPatternPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    List<PaymentPatternPo> selectByExample(PaymentPatternPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    PaymentPatternPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentPatternPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_payment_pattern
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentPatternPo record);
}